### PR TITLE
fix, tests

### LINKED ISSUE #49: Check behavior for maintainers and admins
While working on the documentation, we need to double check the behavior for maintainers and admins. In the [Readme](README.md), it's currently written:

> Note that the Open Collective Bot won't comment on issues opened by maintainers or other admins of your Collective.

I could not verify that behavior by reading the code or tests. If this is confirmed, we need to support that. 

@maticzav can you provide your input?

### PR DESCRIPTION
**Pull request by maticzav**
@znarf this fixes #49. It was an honest mistake that I forgot about during development. It should be good to go.

The only thing I wanted to do is discuss upfront on how to tackle this in a better manner, but this works as well. I am not very fond of edge cases with many `if` statements because they often lead to problems in upcoming versions.

With this PR admins will no longer receive messages when they open issues or have their labels removed when they set them in an issue regardless of the configuration.

### CODE REVIEW

File: src/backers.ts [hunk 1]
```diff
@@ -14,17 +14,23 @@ export function getCollectiveBackerTiers(
...
-  const tiers = allBackers.reduce<Tier[]>((acc, member) => {
-    if (!member.github) return acc
+): Tier[] | null {
+  const tiers = allBackers.reduce<Tier[] | null>((acc, member) => {
+    if (!member.github || acc === null) return acc
 
     const githubName = stripGithubName(member.github)
     const isMember = [...backerOrganisations, backerName].some(is(githubName))
 
+    /* Tiers */
```
Comment (znarf) [inline src/backers.ts:24]: In the case of @Betree, he was an 'ADMIN' and a 'BACKER' at the same time. For that reason I would check ADMIN before checking tiers.

File: src/backers.ts [hunk 2]
```diff
@@ -14,17 +14,23 @@ export function getCollectiveBackerTiers(
...
     if (isMember && member.role === 'BACKER' && member.tier) {
       return uniq([...acc, member.tier])
     }
 
+    /* Admins, Contributors */
+    if (isMember && ['HOST', 'ADMIN', 'CONTRIBUTOR'].includes(member.role)) {
```
Comment (znarf) [inline src/backers.ts:30]: Out of caution, I'll double check the definition of CONTRIBUTOR.

File: src/backers.ts (hunk 1 above)
Comment (maticzav) [reply src/backers.ts:24]: It doesn't matter because once it hits `null` it stays `null`; therefore, there's no difference in the order. Good catch, by the way, I had to double check if I had right thinking process.

File: src/backers.ts (hunk 2 above)
Comment (maticzav) [reply src/backers.ts:30]: 💯

Comment (znarf) [reply src/backers.ts:30]: Looks like you get the CONTRIBUTOR role when submitting an expense. So, it seems right.

File: src/backers.ts (hunk 1 above)
Comment (znarf) [reply src/backers.ts:24]: It is this way because of the early exit right? `if (!member.github || acc === null) return acc`

**Comment by maticzav** [comment]
Everything seems resolved! Are you ok with me merging this?

**Review by znarf — APPROVED** [review]

**Comment by znarf** [comment]
Good for me!

File: src/backers.ts (hunk 1 above)
Comment (maticzav) [reply src/backers.ts:24]: yup, exactly 🙂
